[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
ignored_error_codes = [3860, 5574] # contract-size
fs_permissions = [
  { access = "read", path = "./utils/assets/" },
  { access = "read-write", path = "./utils/assets/test_output" },
  { access = "read-write", path = "./deployment-manifest.json" },
  { access = "read-write", path = "./protocolSnapshot.json" },
  { access = "read", path = "out" },
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[invariant]
call_override = false
fail_on_revert = true
runs = 500
depth = 50
# failure_persist_dir = "/dev/null" # XXX circumvent this half-baked Foundry feature
shrink_run_limit = 0 # XXX shrinking is super broken, results in completely wrong repro sequence

[profile.ci]
optimizer = true

[profile.ci.invariant]
shrink_run_limit = 0 # takes too damn long to shrink, don't waste Github minutes


[profile.default.rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
scroll = "https://rpc.scroll.io"
optimism = "wss://optimism-rpc.publicnode.com"
swellchain = "https://swell-mainnet.alt.technology"
tenderly-mainnet = "${TENDERLY_RPC_URL}"

[profile.e2e]
# Allows us to .gitignore broadcast logs of E2E deployments
broadcast = 'broadcast-e2e'
# As we are running tests in a fork that uses the same chain ID as the forked chain, it is important not to be caching
# any storage, as any new state on top of the forked block is ephemeral and should not be commingled with real state.
# Anvil is going to be caching any storage requests that hit the underlying RPC anyway.
no_storage_caching = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.fast]
optimizer = true
# optional profile for faster forge builds avoiding original BOLD tests
skip = [
  # disable a lot of BOLD's source
  # these are either things we don't use (e.g. original price feeds),
  # or that are used as dependencies, and therefore end up compiled as part of other files
  'src/Zappers/*',
  'src/Dependencies/*',
  'src/PriceFeeds/*',
  'src/Types/*',

  # disable bold's original test suite
  # (CI will still run it)
  'src/test/TestContracts/*',
  'src/test/Utils/*',
  'src/MockInterestRouter.sol',
  '*/AnchoredInvariantsTest.t.sol',
  '*/interestRateAggregate.t.sol',
  '*/SPInvariants.t.sol',
  '*/AnchoredSPInvariantsTest.t.sol',
  '*/interestRateBasic.t.sol',
  '*/stabilityPool.t.sol',
  '*/basicOps.t.sol',
  '*/Invariants.t.sol',
  '*/batchManagementFee.t.sol',
  '*/liquidationCosts.t.sol',
  '*/troveManager.t.sol',
  '*/BoldToken.t.sol',
  '*/liquidations.t.sol',
  '*/troveNFT.t.sol',
  '*/borrowerOperations.t.sol',
  '*/liquidationsLST.t.sol',
  '*/borrowerOperationsOnBehalfTroveManagament.sol',
  '*/multicollateral.t.sol',
  '*/zapperGasComp.t.sol',
  '*/criticalThreshold.t.sol',
  '*/OracleMainnet.t.sol',
  # '*/zapperLeverage.t.sol',
  '*/deployment.t.sol',
  '*/zapperWETH.t.sol',
  '*/events.t.sol',
  '*/rebasingBatchShares.t.sol',
  '*/HintHelpers.t.sol',
  '*/redemptions.t.sol',
  '*/interestBatchManagement.t.sol',
  '*/shutdown.t.sol',
  '*/interestIndividualDelegation.t.sol',
  '*/SortedTroves.t.sol',
]

[profile.justsrc]
optimizer = true
skip = [
  'test/*',
  'script/*',
]
